fixtures:
  repositories:
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
    epel: https://github.com/stahnma/puppet-module-epel.git
    lsb: https://github.com/nanliu/puppet-lsb.git
